development:
  adapter: postgresql
  database: rgsoc_campaign_development
  host: localhost

test:
  adapter: postgresql
  database: rgsoc_campaign_test
  host: localhost
  min_messages: error

production:
  adapter: postgresql
  database: rgsoc_production
